
import React, { useState, useEffect, useRef } from 'react';
import { Icons } from '../components/icons';
import { Button } from '../components/Button';
import { Card } from '../components/Card';
import { Input } from '../components/Input';
import { sha512, generateFloat, generateMines, generatePlinkoPath } from '../lib/crypto';

// --- TYPES & CONSTANTS ---
const DEFINITIONS: Record<string, string> = {
    "Server Seed": "Generated by the house. Hashed before the round to prove we can't change it.",
    "Client Seed": "Provided by you. Ensures we can't predict the outcome.",
    "Nonce": "A transaction counter (1, 2, 3...). Ensures every bet is unique.",
    "Hash": "The encrypted 'lock' on the Server Seed. Matches the seed only if fair.",
    "HMAC": "Hash-based Message Authentication Code. The math combining your seed and ours."
};

// --- VISUAL COMPONENTS ---

const TermTooltip = ({ term, children }: { term: string, children?: React.ReactNode }) => {
    const [show, setShow] = useState(false);
    return (
        <div className="relative inline-block" onMouseEnter={() => setShow(true)} onMouseLeave={() => setShow(false)}>
            <span className="cursor-help border-b border-dotted border-neon-surge/50 hover:text-neon-surge transition-colors">{children}</span>
            <div className={`absolute bottom-full left-1/2 -translate-x-1/2 mb-2 w-64 p-4 bg-[#0c0c0e] border border-neon-surge/30 rounded-xl shadow-[0_10px_40px_-10px_rgba(0,0,0,0.8)] z-50 transition-all duration-200 transform origin-bottom ${show ? 'opacity-100 scale-100 translate-y-0' : 'opacity-0 scale-95 translate-y-2 pointer-events-none'}`}>
                <div className="flex items-center gap-2 mb-2 border-b border-[#222] pb-2">
                    <Icons.Info className="w-3 h-3 text-neon-surge" />
                    <p className="text-[10px] font-orbitron text-white uppercase font-bold tracking-wider">{term}</p>
                </div>
                <p className="text-xs font-rajdhani text-text-secondary leading-relaxed">{DEFINITIONS[term]}</p>
                <div className="absolute top-full left-1/2 -translate-x-1/2 border-8 border-transparent border-t-[#0c0c0e]"></div>
            </div>
        </div>
    );
};

const InteractiveBackground = () => {
    const canvasRef = useRef<HTMLCanvasElement>(null);
    const mouseRef = useRef({ x: -1000, y: -1000 });

    useEffect(() => {
        const canvas = canvasRef.current;
        if (!canvas) return;
        const ctx = canvas.getContext('2d');
        if (!ctx) return;

        let animationFrameId: number;
        let particles: any[] = [];

        const resize = () => {
            canvas.width = window.innerWidth;
            canvas.height = window.innerHeight;
            initParticles();
        };

        const initParticles = () => {
            particles = [];
            const count = Math.floor((window.innerWidth * window.innerHeight) / 20000);
            for (let i = 0; i < count; i++) {
                particles.push({
                    x: Math.random() * canvas.width,
                    y: Math.random() * canvas.height,
                    vx: (Math.random() - 0.5) * 0.3,
                    vy: (Math.random() - 0.5) * 0.3,
                    size: Math.random() * 1.5 + 0.5,
                    color: Math.random() > 0.95 ? '#00FFC0' : '#222222'
                });
            }
        };

        const animate = () => {
            ctx.clearRect(0, 0, canvas.width, canvas.height);
            
            // Draw static grid
            ctx.strokeStyle = 'rgba(255, 255, 255, 0.02)';
            ctx.lineWidth = 1;
            const gridSize = 40;
            for (let x = 0; x < canvas.width; x += gridSize) {
                ctx.beginPath();
                ctx.moveTo(x, 0);
                ctx.lineTo(x, canvas.height);
                ctx.stroke();
            }
            for (let y = 0; y < canvas.height; y += gridSize) {
                ctx.beginPath();
                ctx.moveTo(0, y);
                ctx.lineTo(canvas.width, y);
                ctx.stroke();
            }

            particles.forEach(p => {
                p.x += p.vx;
                p.y += p.vy;

                // Mouse interaction
                const dx = mouseRef.current.x - p.x;
                const dy = mouseRef.current.y - p.y;
                const distance = Math.sqrt(dx * dx + dy * dy);
                const maxDist = 200;

                if (distance < maxDist) {
                    const force = (maxDist - distance) / maxDist;
                    p.vx -= (dx / distance) * force * 0.5;
                    p.vy -= (dy / distance) * force * 0.5;
                }

                // Boundary wrap
                if (p.x < 0) p.x = canvas.width;
                if (p.x > canvas.width) p.x = 0;
                if (p.y < 0) p.y = canvas.height;
                if (p.y > canvas.height) p.y = 0;

                ctx.beginPath();
                ctx.arc(p.x, p.y, p.size, 0, Math.PI * 2);
                ctx.fillStyle = p.color;
                ctx.fill();
            });

            animationFrameId = requestAnimationFrame(animate);
        };

        const handleMouseMove = (e: MouseEvent) => {
            mouseRef.current = { x: e.clientX, y: e.clientY };
        };

        window.addEventListener('resize', resize);
        window.addEventListener('mousemove', handleMouseMove);
        
        resize();
        animate();

        return () => {
            window.removeEventListener('resize', resize);
            window.removeEventListener('mousemove', handleMouseMove);
            cancelAnimationFrame(animationFrameId);
        };
    }, []);

    return <canvas ref={canvasRef} className="fixed inset-0 pointer-events-none z-0 opacity-40" />;
};

const ScrambleText = ({ text, className, revealSpeed = 50 }: { text: string, className?: string, revealSpeed?: number }) => {
    const [display, setDisplay] = useState(text);
    const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789@#$%&';

    useEffect(() => {
        let iterations = 0;
        const interval = setInterval(() => {
            setDisplay(prev => 
                text.split('').map((char, index) => {
                    if (index < iterations) return text[index];
                    return chars[Math.floor(Math.random() * chars.length)];
                }).join('')
            );
            if (iterations >= text.length) clearInterval(interval);
            iterations += 0.5;
        }, revealSpeed);
        return () => clearInterval(interval);
    }, [text, revealSpeed]);

    return <span className={`${className} font-jetbrains-mono`}>{display}</span>;
};

// --- MAIN PAGE ---

const ProvablyFairPage: React.FC = () => {
    const [serverSeed, setServerSeed] = useState('a1b2c3d4e5f6789012345678901234567890123456789012345678901234');
    const [clientSeed, setClientSeed] = useState('zap_player_42');
    const [nonce, setNonce] = useState<number>(1);
    const [gameType, setGameType] = useState<'DICE' | 'PLINKO' | 'MINES'>('DICE');
    const [plinkoRows, setPlinkoRows] = useState(16);
    const [minesCount, setMinesCount] = useState(3);
    const [hashedServerSeed, setHashedServerSeed] = useState('');
    const [verifierLog, setVerifierLog] = useState<{ timestamp: string, type: string, result: React.ReactNode }[]>([]);
    const [copied, setCopied] = useState(false);
    const [showStickyGuide, setShowStickyGuide] = useState(true);

    // --- EFFECTS ---
    useEffect(() => {
        if (serverSeed) {
            const hash = sha512(serverSeed);
            setHashedServerSeed(hash);
        }
    }, [serverSeed]);

    const copyToClipboard = (text: string) => {
        navigator.clipboard.writeText(text);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
    };

    // --- VERIFICATION LOGIC WITH VISUAL STEPS ---
    const executeVerify = () => {
        try {
            const timestamp = new Date().toLocaleTimeString([], { hour12: false, hour: '2-digit', minute: '2-digit', second: '2-digit' });
            let steps: React.ReactNode[] = [];
            let rawResult = "";

            // Step 1: HMAC Calc
            steps.push(
                <div key="s1" className="mb-1">
                    <span className="text-purple-400">const</span> <span className="text-white">hmac</span> = <span className="text-blue-400">createHmac</span>(<span className="text-green-400">'sha512'</span>, serverSeed);
                </div>
            );
            steps.push(
                <div key="s2" className="mb-1 pl-4 border-l border-[#333]">
                    <span className="text-[#888]">// Input: {clientSeed}:{nonce}:0</span>
                </div>
            );

            if (gameType === 'DICE') {
                const float = generateFloat(serverSeed, clientSeed, nonce, 0);
                const roll = (float * 10001) / 100;
                rawResult = roll.toFixed(2);

                steps.push(
                    <div key="s3" className="mb-1">
                        <span className="text-purple-400">const</span> float = <span className="text-orange-400">{float.toFixed(8)}</span>;
                    </div>
                );
                 steps.push(
                    <div key="s4" className="mb-1">
                        <span className="text-purple-400">const</span> result = (float * 10001) / 100;
                    </div>
                );
                steps.push(
                    <div key="res" className="mt-2 pt-2 border-t border-[#333] text-neon-surge font-bold">
                        {`=> RETURN ${rawResult}`}
                    </div>
                );

            } else if (gameType === 'PLINKO') {
                const bucket = generatePlinkoPath(serverSeed, clientSeed, nonce, plinkoRows);
                rawResult = bucket.toString();
                
                steps.push(
                    <div key="s3" className="mb-1">
                        <span className="text-[#888]">// Generating Path for {plinkoRows} rows...</span>
                    </div>
                );
                 steps.push(
                    <div key="res" className="mt-2 pt-2 border-t border-[#333] text-neon-surge font-bold">
                        {`=> BUCKET_INDEX: ${rawResult}`}
                    </div>
                );
            } else if (gameType === 'MINES') {
                const mines = generateMines(serverSeed, clientSeed, nonce, minesCount);
                rawResult = mines.join(', ');
                 steps.push(
                    <div key="s3" className="mb-1">
                         <span className="text-[#888]">// Fisher-Yates Shuffle on 25 tiles...</span>
                    </div>
                );
                steps.push(
                    <div key="res" className="mt-2 pt-2 border-t border-[#333] text-neon-surge font-bold break-all">
                        {`=> MINE_POSITIONS: [${rawResult}]`}
                    </div>
                );
            }

            setVerifierLog(prev => [{ timestamp, type: gameType, result: <div>{steps}</div> }, ...prev].slice(0, 50));
        } catch (e) {
            console.error(e);
        }
    };

    return (
        <div className="min-h-screen bg-[#050505] text-white font-rajdhani relative overflow-hidden selection:bg-neon-surge selection:text-black">
            <InteractiveBackground />

            {/* STICKY GUIDE TOGGLE */}
            <div className={`fixed bottom-8 right-8 z-50 transition-all duration-500 ${showStickyGuide ? 'translate-y-0' : 'translate-y-32'}`}>
                <div className="bg-[#0c0c0e] border border-neon-surge/30 rounded-xl p-4 shadow-[0_0_30px_rgba(0,255,192,0.2)] max-w-xs">
                    <div className="flex justify-between items-center mb-2">
                        <h4 className="font-orbitron text-xs font-bold text-white uppercase">Quick Audit Guide</h4>
                        <button onClick={() => setShowStickyGuide(false)} className="text-[#666] hover:text-white"><Icons.X className="w-4 h-4" /></button>
                    </div>
                    <ol className="text-[10px] text-text-secondary space-y-2 font-jetbrains-mono list-decimal list-inside">
                        <li>Get <strong className="text-neon-surge">Unhashed Seed</strong> from game history.</li>
                        <li>Paste into <strong className="text-white">Server Seed</strong> input.</li>
                        <li>Verify output matches game result.</li>
                    </ol>
                </div>
            </div>
            {!showStickyGuide && (
                <button onClick={() => setShowStickyGuide(true)} className="fixed bottom-8 right-8 z-50 bg-neon-surge text-black p-3 rounded-full shadow-lg hover:scale-110 transition-transform">
                    <Icons.HelpCircle className="w-6 h-6" />
                </button>
            )}

            <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-16 relative z-10">
                
                {/* HERO */}
                <header className="text-center mb-24">
                    <div className="inline-flex items-center gap-3 px-4 py-1.5 border border-neon-surge/30 rounded-full bg-neon-surge/5 mb-8 backdrop-blur-sm animate-fade-up">
                         <span className="relative flex h-2 w-2">
                            <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-neon-surge opacity-75"></span>
                            <span className="relative inline-flex rounded-full h-2 w-2 bg-neon-surge"></span>
                        </span>
                        <span className="text-xs font-orbitron text-neon-surge uppercase tracking-[0.2em] font-bold">Cryptographic Integrity: Active</span>
                    </div>
                    
                    <h1 className="font-orbitron text-5xl md:text-8xl font-black text-white uppercase tracking-tight leading-none mb-6 animate-fade-up" style={{ animationDelay: '0.1s' }}>
                        TRUST IS <span className="relative inline-block mx-2">
                            <span className="absolute inset-x-0 top-1/2 h-1 bg-red-500 -rotate-6"></span>
                            <span className="text-[#444]">DEAD</span>
                        </span>
                        <span className="text-neon-surge text-glow">MATH.</span>
                    </h1>
                    
                    <p className="text-lg md:text-xl text-text-secondary font-medium leading-relaxed max-w-2xl mx-auto animate-fade-up font-jetbrains-mono" style={{ animationDelay: '0.2s' }}>
                        We replaced the "Black Box" with open-source verification. <br/>
                        Don't just play. <TermTooltip term="Hash">Verify</TermTooltip> every outcome.
                    </p>

                    <div className="flex justify-center gap-4 mt-10 animate-fade-up" style={{ animationDelay: '0.3s' }}>
                         <Button 
                            onClick={() => document.getElementById('verifier')?.scrollIntoView({ behavior: 'smooth' })}
                            className="bg-neon-surge text-black font-bold font-orbitron uppercase tracking-widest px-8 shadow-[0_0_20px_rgba(0,255,192,0.3)] hover:scale-105"
                        >
                            Start Audit
                        </Button>
                        <Button variant="ghost" className="border border-[#333] text-text-secondary hover:text-white font-orbitron uppercase tracking-widest px-8">
                            <Icons.Code className="w-4 h-4 mr-2" /> View Source
                        </Button>
                    </div>
                </header>

                {/* EDUCATIONAL CARDS */}
                <section className="mb-24 animate-fade-up" style={{ animationDelay: '0.4s' }}>
                    <div className="grid grid-cols-1 md:grid-cols-3 gap-6 relative">
                        {/* Connector Line */}
                        <div className="hidden md:block absolute top-10 left-[16%] right-[16%] h-0.5 bg-gradient-to-r from-transparent via-neon-surge/20 to-transparent -z-10"></div>

                        <Card className="bg-[#0c0c0e] border-[#333] hover:border-neon-surge/50 transition-all p-8 group relative overflow-hidden">
                            <div className="absolute -top-10 -right-10 w-32 h-32 bg-blue-500/5 rounded-full blur-3xl group-hover:bg-blue-500/10 transition-all"></div>
                            <div className="w-12 h-12 bg-[#1a1a1a] rounded-lg border border-[#333] flex items-center justify-center mb-6 text-blue-400 shadow-lg group-hover:text-white group-hover:bg-blue-500 transition-all">
                                <span className="font-orbitron font-bold text-xl">1</span>
                            </div>
                            <h3 className="text-lg font-bold text-white font-orbitron uppercase mb-2 group-hover:text-blue-400 transition-colors">The Shuffle</h3>
                            <p className="text-sm text-text-secondary leading-relaxed">
                                We generate a random <TermTooltip term="Server Seed">Server Seed</TermTooltip>. Before you bet, we hash it and show you the fingerprint. This proves we committed to the result beforehand.
                            </p>
                        </Card>

                        <Card className="bg-[#0c0c0e] border-[#333] hover:border-neon-surge/50 transition-all p-8 group relative overflow-hidden">
                            <div className="absolute -top-10 -right-10 w-32 h-32 bg-neon-surge/5 rounded-full blur-3xl group-hover:bg-neon-surge/10 transition-all"></div>
                            <div className="w-12 h-12 bg-[#1a1a1a] rounded-lg border border-[#333] flex items-center justify-center mb-6 text-neon-surge shadow-lg group-hover:text-black group-hover:bg-neon-surge transition-all">
                                <span className="font-orbitron font-bold text-xl">2</span>
                            </div>
                            <h3 className="text-lg font-bold text-white font-orbitron uppercase mb-2 group-hover:text-neon-surge transition-colors">The Cut</h3>
                            <p className="text-sm text-text-secondary leading-relaxed">
                                You provide a <TermTooltip term="Client Seed">Client Seed</TermTooltip>. This is your input. Since we don't know your seed in advance, we cannot manipulate the random generation.
                            </p>
                        </Card>

                         <Card className="bg-[#0c0c0e] border-[#333] hover:border-neon-surge/50 transition-all p-8 group relative overflow-hidden">
                            <div className="absolute -top-10 -right-10 w-32 h-32 bg-purple-500/5 rounded-full blur-3xl group-hover:bg-purple-500/10 transition-all"></div>
                            <div className="w-12 h-12 bg-[#1a1a1a] rounded-lg border border-[#333] flex items-center justify-center mb-6 text-purple-400 shadow-lg group-hover:text-white group-hover:bg-purple-500 transition-all">
                                <span className="font-orbitron font-bold text-xl">3</span>
                            </div>
                            <h3 className="text-lg font-bold text-white font-orbitron uppercase mb-2 group-hover:text-purple-400 transition-colors">The Reveal</h3>
                            <p className="text-sm text-text-secondary leading-relaxed">
                                Post-game, we reveal the raw Server Seed. You verify that it matches the initial <TermTooltip term="Hash">Hash</TermTooltip> and reproduces the exact same game result.
                            </p>
                        </Card>
                    </div>
                </section>

                {/* VERIFIER CONSOLE */}
                <section id="verifier" className="animate-fade-up" style={{ animationDelay: '0.5s' }}>
                    <div className="flex items-end justify-between mb-4">
                         <h2 className="text-xl font-orbitron font-bold text-white uppercase tracking-wide flex items-center gap-3">
                            <Icons.Terminal className="w-5 h-5 text-neon-surge" /> Tactical Verifier
                        </h2>
                    </div>

                    <div className="bg-[#0c0c0e] border border-neon-surge/30 rounded-xl overflow-hidden shadow-[0_0_50px_rgba(0,255,192,0.05)] grid grid-cols-1 lg:grid-cols-12 min-h-[600px]">
                        
                        {/* INPUTS */}
                        <div className="lg:col-span-4 p-6 md:p-8 border-b lg:border-b-0 lg:border-r border-[#333] bg-[#080808] flex flex-col">
                            <div className="space-y-6 flex-1">
                                
                                <div>
                                    <label className="block text-[10px] font-orbitron text-text-tertiary uppercase tracking-widest mb-3">
                                        Protocol
                                    </label>
                                    <div className="flex flex-wrap gap-2">
                                        {['DICE', 'PLINKO', 'MINES'].map(type => (
                                            <button
                                                key={type}
                                                onClick={() => setGameType(type as any)}
                                                className={`flex-1 py-2.5 rounded text-[10px] font-bold font-orbitron uppercase transition-all border ${gameType === type ? 'bg-neon-surge text-black border-neon-surge' : 'bg-[#14131c] text-text-tertiary border-[#333] hover:text-white'}`}
                                            >
                                                {type}
                                            </button>
                                        ))}
                                    </div>
                                </div>

                                <div className="space-y-4">
                                    <div>
                                        <label className="block text-[10px] font-orbitron text-neon-surge uppercase tracking-widest mb-2">
                                            Server Seed (Unhashed)
                                        </label>
                                        <Input 
                                            value={serverSeed}
                                            onChange={(e) => setServerSeed(e.target.value)}
                                            className="font-jetbrains-mono text-xs bg-[#111] border-[#333] h-10 focus:border-neon-surge text-white"
                                            placeholder="Paste revealed seed..."
                                        />
                                        <div className="mt-2 flex items-center gap-2 px-2 py-1.5 bg-[#111] rounded border border-[#222] overflow-hidden">
                                            <div className="text-[9px] text-text-tertiary uppercase font-orbitron shrink-0">Active Hash</div>
                                            <div className="text-[9px] font-jetbrains-mono text-text-secondary truncate opacity-70 w-full">
                                                <ScrambleText text={hashedServerSeed || 'Waiting...'} />
                                            </div>
                                        </div>
                                    </div>

                                    <div>
                                        <label className="block text-[10px] font-orbitron text-text-tertiary uppercase tracking-widest mb-2">
                                            Client Seed
                                        </label>
                                        <Input 
                                            value={clientSeed}
                                            onChange={(e) => setClientSeed(e.target.value)}
                                            className="font-jetbrains-mono text-xs bg-[#111] border-[#333] h-10 focus:border-neon-surge text-white"
                                        />
                                    </div>

                                    <div className="grid grid-cols-2 gap-4">
                                        <div>
                                            <label className="block text-[10px] font-orbitron text-text-tertiary uppercase tracking-widest mb-2">Nonce</label>
                                            <Input 
                                                type="number" 
                                                value={nonce}
                                                onChange={(e) => setNonce(Number(e.target.value))}
                                                className="font-jetbrains-mono bg-[#111] border-[#333] h-10 focus:border-neon-surge text-white"
                                            />
                                        </div>
                                        {gameType === 'PLINKO' && (
                                            <div>
                                                <label className="block text-[10px] font-orbitron text-text-tertiary uppercase tracking-widest mb-2">Rows</label>
                                                <Input 
                                                    type="number" 
                                                    value={plinkoRows}
                                                    onChange={(e) => setPlinkoRows(Number(e.target.value))}
                                                    className="font-jetbrains-mono bg-[#111] border-[#333] h-10 focus:border-neon-surge text-white"
                                                />
                                            </div>
                                        )}
                                        {gameType === 'MINES' && (
                                             <div>
                                                <label className="block text-[10px] font-orbitron text-text-tertiary uppercase tracking-widest mb-2">Mines</label>
                                                <Input 
                                                    type="number" 
                                                    value={minesCount}
                                                    onChange={(e) => setMinesCount(Number(e.target.value))}
                                                    className="font-jetbrains-mono bg-[#111] border-[#333] h-10 focus:border-neon-surge text-white"
                                                />
                                            </div>
                                        )}
                                    </div>
                                </div>

                                <Button 
                                    onClick={executeVerify} 
                                    className="w-full mt-auto h-12 font-orbitron font-black text-xs uppercase tracking-[0.2em] bg-neon-surge text-black hover:bg-white shadow-neon-glow-sm"
                                >
                                    Execute Verification
                                </Button>
                            </div>
                        </div>

                        {/* OUTPUT */}
                        <div className="lg:col-span-8 bg-[#050505] p-6 md:p-8 font-jetbrains-mono text-xs flex flex-col relative">
                            <div className="flex items-center justify-between border-b border-[#222] pb-4 mb-4">
                                <div className="flex items-center gap-3">
                                    <div className="w-3 h-3 rounded-full bg-red-500"></div>
                                    <div className="w-3 h-3 rounded-full bg-yellow-500"></div>
                                    <div className="w-3 h-3 rounded-full bg-green-500"></div>
                                    <span className="ml-2 text-text-tertiary uppercase tracking-widest text-[10px]">Audit Terminal</span>
                                </div>
                                <button onClick={() => setVerifierLog([])} className="text-[10px] text-text-tertiary hover:text-white uppercase transition-colors">Clear Log</button>
                            </div>

                            <div className="flex-1 overflow-y-auto custom-scrollbar space-y-4 pr-2">
                                {verifierLog.length === 0 ? (
                                    <div className="h-full flex flex-col items-center justify-center text-[#222] space-y-4 select-none">
                                        <Icons.Code className="w-24 h-24 opacity-20" />
                                        <span className="uppercase tracking-widest font-bold">READY FOR INPUT</span>
                                    </div>
                                ) : (
                                    verifierLog.map((log, i) => (
                                        <div key={i} className={`group relative p-4 rounded border-l-2 transition-all duration-300 ${i === 0 ? 'bg-[#111] border-neon-surge shadow-lg' : 'border-[#333] opacity-50'}`}>
                                            <div className="flex items-center justify-between mb-2 text-[10px] text-text-tertiary uppercase">
                                                <span className="font-bold text-neon-surge">[{log.timestamp}] {log.type}_VERIFY_INIT</span>
                                                <button onClick={() => copyToClipboard(JSON.stringify(log.result))} className="opacity-0 group-hover:opacity-100 hover:text-white transition-opacity">
                                                    {copied ? "COPIED" : "COPY JSON"}
                                                </button>
                                            </div>
                                            <div className="text-sm text-text-secondary font-medium leading-relaxed font-jetbrains-mono">
                                                {log.result}
                                            </div>
                                        </div>
                                    ))
                                )}
                            </div>
                        </div>
                    </div>
                </section>

                {/* TRUST FOOTER */}
                <section className="mt-24 grid grid-cols-1 md:grid-cols-2 gap-12 items-center animate-fade-up">
                     <div>
                         <h2 className="text-2xl font-orbitron font-bold text-white uppercase mb-6">Why This Matters</h2>
                         <div className="space-y-6">
                             <div className="flex gap-4">
                                 <div className="p-3 bg-[#1a1a1a] rounded-lg h-fit border border-[#333]"><Icons.Lock className="w-5 h-5 text-neon-surge" /></div>
                                 <div>
                                     <h4 className="text-white font-bold font-orbitron uppercase mb-1 text-sm">Trustless Architecture</h4>
                                     <p className="text-xs text-text-secondary">You don't need to trust the house. You trust the cryptographic math that powers the internet.</p>
                                 </div>
                             </div>
                             <div className="flex gap-4">
                                 <div className="p-3 bg-[#1a1a1a] rounded-lg h-fit border border-[#333]"><Icons.Database className="w-5 h-5 text-neon-surge" /></div>
                                 <div>
                                     <h4 className="text-white font-bold font-orbitron uppercase mb-1 text-sm">Immutable History</h4>
                                     <p className="text-xs text-text-secondary">Seeds and hashes are generated before the bet. They cannot be altered retroactively without breaking the chain.</p>
                                 </div>
                             </div>
                         </div>
                     </div>
                     <div className="bg-[#0c0c0e] p-8 rounded-2xl border border-[#333] text-center">
                         <h3 className="text-lg font-orbitron font-bold text-white uppercase mb-4">Open Source Protocol</h3>
                         <p className="text-xs text-text-secondary mb-8 font-rajdhani leading-relaxed">
                             Our Provably Fair algorithms are public. Developers and security researchers can verify our implementation on GitHub.
                         </p>
                         <div className="flex flex-col sm:flex-row gap-4 justify-center">
                             <Button variant="ghost" className="border border-[#333] text-white hover:text-black hover:bg-white font-orbitron uppercase text-[10px] tracking-wider h-10">
                                 <Icons.Code className="w-3 h-3 mr-2" /> Github Repo
                             </Button>
                             <Button className="bg-neon-surge text-black font-orbitron uppercase text-[10px] tracking-wider font-bold shadow-neon-glow-sm h-10">
                                 Audit Certificate
                             </Button>
                         </div>
                     </div>
                </section>

            </div>
        </div>
    );
};

export default ProvablyFairPage;
